apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080        # service port
      targetPort: 8080  # port of the pod
  type: ClusterIP        # Type of service
  selector:
    app: backend-deploy     #### to be match with the right deployment