apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: {{ .Values.frontend.label }}
  ports:
    - protocol: TCP
      port: 80  # service port
      targetPort: 80  # port of the pod 
  type: {{ .Values.frontend.service.type }}  # Type of service