apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: {{ .Values.mysql.label }}
  type: {{ .Values.mysql.service.type }}
  ports:
    - protocol: TCP
      port: 3306