version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/lib/jenkins/
    restart: always

volumes:
  jenkins_data:
    driver: local
