version: '3.7'
services:
  
  sonarqube:
    image: sonarqube:latest
    container_name: sonar
    depends_on:
      - sonar-database
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-database:5432/sonarqube
    ports :
      - 9010:9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  sonar-database:
    container_name: sonarqube-database
    image: postgres:12
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
    volumes:
      - sonarqube_database:/var/lib/postgresql
      - sonarqube_database_data:/var/lib/postgresql/data
    ports:
      -   5432:5432

volumes:
  sonarqube_database_data:
  sonarqube_logs:
  sonarqube_data:
  sonarqube_database:
  sonarqube_extensions:
